### ISSUE TITLE
"Error loading rule 'csf-no-use-before-define': noUse is not a function"

### ISSUE THREAD

**Issue by bryceosterhaus** [natecavanaugh/check-source-formatting#14]
Updated to 2.0.0-rc.4 via @next. Unable to run now due to error below

```
Unhandled rejection TypeError: Error while loading rule 'csf-no-use-before-define': noUse is not a function
    at module.exports (/usr/local/lib/node_modules/check-source-formatting/lib/lint_js_rules/no_use_before_define.js:49:20)
    at /usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/eslint.js:808:25
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/eslint.js:780:16)
    at runLinter (/usr/local/lib/node_modules/check-source-formatting/lib/lint_js.js:37:23)
    at module.exports (/usr/local/lib/node_modules/check-source-formatting/lib/lint_js.js:58:9)
    at Formatter.JS.Formatter.create._lint (/usr/local/lib/node_modules/check-source-formatting/lib/js.js:109:20)
    at Formatter.JS.Formatter.create.format (/usr/local/lib/node_modules/check-source-formatting/lib/js.js:45:10)
    at /usr/local/lib/node_modules/check-source-formatting/lib/html.js:201:26
    at Array.map (native)
    at Formatter.HTML.Formatter.create.formatJs (/usr/local/lib/node_modules/check-source-formatting/lib/html.js:199:25)
    at Formatter.HTML.Formatter.create.parseJs (/usr/local/lib/node_modules/check-source-formatting/lib/html.js:219:25)
    at Formatter.HTML.Formatter.create.format (/usr/local/lib/node_modules/check-source-formatting/lib/html.js:127:14)
    at _.create.processFileData (/usr/local/lib/node_modules/check-source-formatting/lib/cli.js:230:29)
    at _.create.formatFile (/usr/local/lib/node_modules/check-source-formatting/lib/cli.js:133:21)
    at _.create.onRead (/usr/local/lib/node_modules/check-source-formatting/lib/cli.js:185:16)
```

**Comment by natecavanaugh** [comment]
Fixed via 5cb0614. Just run `npm install -g check-source-formatting@next` and you're good to go.

Thanks Bryce!
