### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by bryceosterhaus** [natecavanaugh/check-source-formatting#18]
I have noticed that I sometimes get this error. I'm not sure exactly what file or line of code is causing this. I know that really doesn't help much, but maybe it is as simple as just checking if `a` and `b` are defined first before comparing them.

```
Unhandled rejection TypeError: Cannot read property 'toLowerCase' of undefined
    at compareAlpha (/usr/local/lib/node_modules/check-source-formatting/lib/rule_utils.js:48:8)
    at exports.naturalCompare (/usr/local/lib/node_modules/check-source-formatting/lib/rule_utils.js:83:12)
    at /usr/local/lib/node_modules/check-source-formatting/lib/lint_js_rules/sort_vars.js:68:20
    at Array.reduce (native)
    at EventEmitter.Program:exit (/usr/local/lib/node_modules/check-source-formatting/lib/lint_js_rules/sort_vars.js:60:30)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.leaveNode (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:23)
    at CommentEventGenerator.leaveNode (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.traverser.traverse.leave (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/eslint.js:908:36)
    at Controller.__execute (/usr/local/lib/node_modules/check-source-formatting/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/check-source-formatting/node_modules/estraverse/estraverse.js:491:28)
    at Controller.Traverser.controller.traverse (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/traverser.js:36:33)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/eslint.js:902:23)
    at runLinter (/usr/local/lib/node_modules/check-source-formatting/lib/lint_js.js:42:23)
```

I debugged it a bit and looks like undefined is being passed from the `'Program:exit'` function

```
var prevName = prev.id.name;
var curName = item.id.name;
```

looks like prev.id is defined, but the name attr is not always defined

**Comment by natecavanaugh** [comment]
Thanks @bryceosterhaus 
Do you have an example file that this occurs for? There might be an ES6 construct coming in that I wasn't aware of.

Thanks Bryce,

**Comment by natecavanaugh** [comment]
@bryceosterhaus Actually, I believe I already fixed this, but just didn't publish it.

Can you do `npm install -g check-source-formatting@next` and see if you still get the error?

If so, go ahead and reopen this.

Thanks Bryce :)

**Comment by bryceosterhaus** [comment]
Looks good to me so far. I never was able to track down a specific file is errored on, but if for some reason it shows up again I will let you know. Thanks!
