### ISSUE TITLE
Throws an error when validating JS containing destructuring of a function's return value.

### ISSUE THREAD

**Issue by mthadley** [natecavanaugh/check-source-formatting#20]
I am seeing the following error when run on this piece of code:
```js
const {a} = myFunc();
```
And now the error:
```
Unhandled rejection TypeError: Cannot read property 'toLowerCase' of undefined
    at compareAlpha (/usr/local/lib/node_modules/check-source-formatting/lib/rule_utils.js:46:8)
    at exports.naturalCompare (/usr/local/lib/node_modules/check-source-formatting/lib/rule_utils.js:81:12)
    at /usr/local/lib/node_modules/check-source-formatting/lib/lint_js_rules/sort_vars.js:68:20
    at Array.reduce (native)
    at EventEmitter.Program:exit (/usr/local/lib/node_modules/check-source-formatting/lib/lint_js_rules/sort_vars.js:60:30)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.leaveNode (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:23)
    at CommentEventGenerator.leaveNode (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.traverser.traverse.leave (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/eslint.js:908:36)
    at Controller.__execute (/usr/local/lib/node_modules/check-source-formatting/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/check-source-formatting/node_modules/estraverse/estraverse.js:491:28)
    at Controller.Traverser.controller.traverse (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/traverser.js:36:33)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/eslint.js:902:23)
    at runLinter (/usr/local/lib/node_modules/check-source-formatting/lib/lint_js.js:42:23)
```

**Comment by natecavanaugh** [comment]
Heya @mthadley 
Sorry for the delay, for some reason I am only now seeing this issue.

I'll take a look at this one, thanks for filing it :)

**Comment by natecavanaugh** [comment]
@mthadley Can you list off the following details for me?

1. Version of the check-source-formatter you're using
2. Version of node.js you're using
3. Any other config settings you might be specifying.

Thanks Mike :)

**Comment by natecavanaugh** [comment]
@mthadley Sorry for the mutiple posts. I believe this is already fixed in the latest version, but can you update to the latest with `npm i -g check-source-formatting@next` and test it again?

If it's good to go, you can close this one out, or if it still doesn't, we can keep it open and keep digging.

**Comment by mthadley** [comment]
I was on `2.0.0-rc.6` and I just updated to `2.0.0-rc.7`. Looks good now. Thanks @natecavanaugh!
